## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
## PostgreSQL
spring.datasource.url=jdbc:postgresql://info2413-postgresql.lonk-ladon.ts.net:5432/info2413
spring.datasource.username=info2413
spring.datasource.password=info2413
## jpa
spring.jpa.open-in-view=true
# create and drop table for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=validate