## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
## PostgreSQL
spring.datasource.url=jdbc:postgresql://info2413-postgresql.lonk-ladon.ts.net:5432/info2413
spring.datasource.username=info2413
spring.datasource.password=info2413
## jpa
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

## logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG
logging.level.com.fasterxml.jackson=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG