CREATE TABLE account_publication
(
    waitlist_position   SMALLINT,
    account_id_account  INTEGER NOT NULL,
    isbn_13_publication BIGINT  NOT NULL,
    CONSTRAINT pk_accountpublication PRIMARY KEY (account_id_account, isbn_13_publication)
);

CREATE TABLE book_copy
(
    serial_barcode      INTEGER NOT NULL,
    date_acquired       date,
    isbn_13_publication BIGINT  NOT NULL,
    CONSTRAINT pk_bookcopy PRIMARY KEY (serial_barcode)
);

CREATE TABLE book_copy_condition_notes
(
    note_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    serial_barcode_book_copy INTEGER                                  NOT NULL,
    condition_notes          TEXT                                     NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bookcopyconditionnotes PRIMARY KEY (note_id)
);

CREATE TABLE borrow_renewal_date
(
    borrow_id_borrow INTEGER NOT NULL,
    renewal_date     date,
    CONSTRAINT pk_borrowrenewaldate PRIMARY KEY (borrow_id_borrow)
);

CREATE TABLE library_card
(
    card_number        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valid              BOOLEAN,
    account_id_account INTEGER,
    CONSTRAINT pk_librarycard PRIMARY KEY (card_number)
);

CREATE TABLE publication_author
(
    author_id_author    INTEGER NOT NULL,
    isbn_13_publication BIGINT  NOT NULL,
    CONSTRAINT pk_publicationauthor PRIMARY KEY (author_id_author, isbn_13_publication)
);

CREATE TABLE publication_publication
(
    isbn_13_publication  BIGINT NOT NULL,
    isbn_13_publication1 BIGINT NOT NULL,
    CONSTRAINT pk_publicationpublication PRIMARY KEY (isbn_13_publication, isbn_13_publication1)
);

ALTER TABLE borrow
    ADD serial_barcode_book_copy INTEGER;

ALTER TABLE hold
    ADD serial_barcode_book_copy INTEGER;

ALTER TABLE account_publication
    ADD CONSTRAINT FK_ACCOUNTPUBLICATION_ON_ACCOUNT_ID_ACCOUNT FOREIGN KEY (account_id_account) REFERENCES account (account_id);

ALTER TABLE account_publication
    ADD CONSTRAINT FK_ACCOUNTPUBLICATION_ON_ISBN_13_PUBLICATION FOREIGN KEY (isbn_13_publication) REFERENCES publication (isbn_13);

ALTER TABLE book_copy
    ADD CONSTRAINT FK_BOOKCOPY_ON_ISBN_13_PUBLICATION FOREIGN KEY (isbn_13_publication) REFERENCES publication (isbn_13);

ALTER TABLE library_card
    ADD CONSTRAINT FK_LIBRARYCARD_ON_ACCOUNT_ID_ACCOUNT FOREIGN KEY (account_id_account) REFERENCES account (account_id);

ALTER TABLE publication_author
    ADD CONSTRAINT FK_PUBLICATIONAUTHOR_ON_AUTHOR_ID_AUTHOR FOREIGN KEY (author_id_author) REFERENCES author (author_id);

ALTER TABLE publication_author
    ADD CONSTRAINT FK_PUBLICATIONAUTHOR_ON_ISBN_13_PUBLICATION FOREIGN KEY (isbn_13_publication) REFERENCES publication (isbn_13);

ALTER TABLE publication_publication
    ADD CONSTRAINT FK_PUBLICATIONPUBLICATION_ON_ISBN_13_PUBLICATION FOREIGN KEY (isbn_13_publication) REFERENCES publication (isbn_13);

ALTER TABLE publication_publication
    ADD CONSTRAINT FK_PUBLICATIONPUBLICATION_ON_ISBN_13_PUBLICATION1 FOREIGN KEY (isbn_13_publication1) REFERENCES publication (isbn_13);

DROP TABLE AccountPublication CASCADE;

DROP TABLE BookCopy CASCADE;

DROP TABLE BookCopyConditionNotes CASCADE;

DROP TABLE BorrowRenewalDate CASCADE;

DROP TABLE LibraryCard CASCADE;

DROP TABLE PublicationAuthor CASCADE;

DROP TABLE PublicationPublication CASCADE;

ALTER TABLE Borrow
DROP
COLUMN serial_barcode_BookCopy;

ALTER TABLE Hold
DROP
COLUMN serial_barcode_BookCopy;

DROP SEQUENCE Account_account_id_seq CASCADE;

DROP SEQUENCE Author_author_id_seq CASCADE;

DROP SEQUENCE BookCopyConditionNotes_note_id_seq CASCADE;

DROP SEQUENCE Borrow_borrow_id_seq CASCADE;

DROP SEQUENCE Fine_fine_id_seq CASCADE;

DROP SEQUENCE Hold_book_hold_id_seq CASCADE;

DROP SEQUENCE Payment_payment_id_seq CASCADE;

CREATE SEQUENCE IF NOT EXISTS account_account_id_seq;
ALTER TABLE account
    ALTER COLUMN account_id SET NOT NULL;
ALTER TABLE account
    ALTER COLUMN account_id SET DEFAULT nextval('account_account_id_seq');

ALTER SEQUENCE account_account_id_seq OWNED BY account.account_id;

CREATE SEQUENCE IF NOT EXISTS author_author_id_seq;
ALTER TABLE author
    ALTER COLUMN author_id SET NOT NULL;
ALTER TABLE author
    ALTER COLUMN author_id SET DEFAULT nextval('author_author_id_seq');

ALTER SEQUENCE author_author_id_seq OWNED BY author.author_id;

CREATE SEQUENCE IF NOT EXISTS hold_book_hold_id_seq;
ALTER TABLE hold
    ALTER COLUMN book_hold_id SET NOT NULL;
ALTER TABLE hold
    ALTER COLUMN book_hold_id SET DEFAULT nextval('hold_book_hold_id_seq');

ALTER SEQUENCE hold_book_hold_id_seq OWNED BY hold.book_hold_id;

CREATE SEQUENCE IF NOT EXISTS borrow_borrow_id_seq;
ALTER TABLE borrow
    ALTER COLUMN borrow_id SET NOT NULL;
ALTER TABLE borrow
    ALTER COLUMN borrow_id SET DEFAULT nextval('borrow_borrow_id_seq');

ALTER SEQUENCE borrow_borrow_id_seq OWNED BY borrow.borrow_id;

ALTER TABLE publication
ALTER
COLUMN ebook_url TYPE VARCHAR(255) USING (ebook_url::VARCHAR(255));

CREATE SEQUENCE IF NOT EXISTS fine_fine_id_seq;
ALTER TABLE fine
    ALTER COLUMN fine_id SET NOT NULL;
ALTER TABLE fine
    ALTER COLUMN fine_id SET DEFAULT nextval('fine_fine_id_seq');

ALTER SEQUENCE fine_fine_id_seq OWNED BY fine.fine_id;

ALTER TABLE payment
ALTER
COLUMN payment_amount TYPE DECIMAL USING (payment_amount::DECIMAL);

ALTER TABLE payment
    ALTER COLUMN payment_amount DROP NOT NULL;

CREATE SEQUENCE IF NOT EXISTS payment_payment_id_seq;
ALTER TABLE payment
    ALTER COLUMN payment_id SET NOT NULL;
ALTER TABLE payment
    ALTER COLUMN payment_id SET DEFAULT nextval('payment_payment_id_seq');

ALTER SEQUENCE payment_payment_id_seq OWNED BY payment.payment_id;

ALTER TABLE account
    ADD CONSTRAINT pk_account PRIMARY KEY (account_id);

ALTER TABLE author
    ADD CONSTRAINT pk_author PRIMARY KEY (author_id);

ALTER TABLE borrow
    ADD CONSTRAINT pk_borrow PRIMARY KEY (borrow_id);

ALTER TABLE configuration
    ADD CONSTRAINT pk_configuration PRIMARY KEY (config_key);

ALTER TABLE fine
    ADD CONSTRAINT pk_fine PRIMARY KEY (fine_id);

ALTER TABLE hold
    ADD CONSTRAINT pk_hold PRIMARY KEY (book_hold_id);

ALTER TABLE payment
    ADD CONSTRAINT pk_payment PRIMARY KEY (payment_id);

ALTER TABLE publication
    ADD CONSTRAINT pk_publication PRIMARY KEY (isbn_13);